version: "3.8"
services:

  catalog-service-app:
    depends_on:
      - config-server
      - catalog-postgres-db
    image: "ghcr.io/arpan2402/catalog-service"
    container_name: "catalog-service-app"
    ports:
      - 9001:9001
      - 5005:5005
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=5005
      - SPRING_PROFILES_ACTIVE=container
      - SPRING_DATASOURCE_URL=jdbc:postgresql://catalog-postgres-db/catalog_db
      - APPLICATION_LOADTESTDATA=true
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888

  catalog-postgres-db:
    image: "postgres:14.4"
    container_name: "catalog-postgres-db"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=catalog_db

  config-server:
    image: "ghcr.io/arpan2402/config-server"
    container_name: "config-server"
    ports:
      - 8888:8888
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - SPRING_PROFILES_ACTIVE=container